import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";

import "@/app/globals.css";
import Navbar from "@/components/navbar/AppNavbar";
import Footer from "@/components/footer/AppFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "VirgoLearningAI",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function AppLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased gradient-bg`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
